### ISSUE TITLE
PHP 8.3.3

### ISSUE THREAD

**Issue by ViPErCZ** [contributte/forms-multiplier#90]
Declaration of Contributte\FormMultiplier\Multiplier::setValues($values, bool $erase = false): Contributte\FormMultiplier\Multiplier must be compatible with [Nette\Forms\Container::setValues]

Nette Form 3.2.0

**Comment by jtojnar** [comment]
This has been fixed by https://github.com/contributte/forms-multiplier/commit/9b4e600be60dfbef5861ecd012b0b57d94837d1a

**Comment by radimvaculik** [comment]
@f3l1x Could you make a release, please? 🙏

**Comment by jtojnar** [comment]
The current master is still a bit broken. I am working on a fix but in the meanwhile it might be a good idea to backport https://github.com/contributte/forms-multiplier/commit/9b4e600be60dfbef5861ecd012b0b57d94837d1a and release 4.0.1.

**Comment by radimvaculik** [comment]
@jtojnar Did you manage to fix the bug? Otherwise, we should backport https://github.com/contributte/forms-multiplier/commit/9b4e600be60dfbef5861ecd012b0b57d94837d1a and release 4.0.1. Cheers.

**Comment by jtojnar** [comment]
Not yet. Please give https://github.com/contributte/forms-multiplier/pull/102 a try, will cut a release from it later if nobody complains.

**Comment by jtojnar** [comment]
Released 4.0.1.

By the way, turns out this issue is unrelated to PHP version. It was actually caused by `nette/forms` 3.2.0 [changing the type signature of `Container::setValues`](https://github.com/nette/forms/commit/dffc07dd8de7ef1c2d713ebe62b4786b8275a0bd). Well, I guess this is our bad for overriding `@internal` method.
